# Generated by Django 4.2.7 on 2023-12-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.SmallAutoField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите имя пользователя", max_length=30
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Введите номер телефона",
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Введите адрес проживания", max_length=30
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        help_text="Введите электронную почту",
                        max_length=30,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
