# Generated by Django 4.2.7 on 2023-11-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[('AP', 'Apple'), ('AD', 'Android')], default='AP', max_length=2)),
                ('type', models.CharField(choices=[('SM', 'smartphone'), ('MF', 'mobile_phone')], default='SM', max_length=2)),
                ('system', models.CharField(choices=[('iOS', 'iOS'), ('AD', 'Android')], default='iOS', max_length=7)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
