# Generated by Django 4.2.7 on 2023-11-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[('AP', 'Apple'), ('AD', 'Android')], default='AP', max_length=2)),
                ('type', models.CharField(choices=[('SM', 'smartphone'), ('MF', 'mobile_phone')], default='SM', max_length=2)),
                ('system', models.CharField(choices=[('iOS', 'iOS'), ('AD', 'Android')], default='iOS', max_length=7)),
                ('price', models.IntegerField(default=0)),
            ],
            name='Customer',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите имя пользователя', max_length=30)),
                ('phone', models.CharField(help_text='Введите номер телефона', max_length=12, unique=True)),
                ('address', models.CharField(help_text='Введите адрес проживания', max_length=30)),
                ('email', models.CharField(help_text='Введите электронную почту', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'customer',
                'db_table_comment': 'table about customer',
            },
        ),
    ]
