# Generated by Django 4.2.7 on 2023-12-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_Customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.SmallAutoField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("smartphone", "Смартфон"),
                            ("push_button_telephone", "Кнопочный телефон"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS")],
                        max_length=30,
                    ),
                ),
                ("version_os", models.CharField(max_length=30)),
                ("phone_model", models.CharField(max_length=30)),
                (
                    "cpu",
                    models.CharField(help_text="процессор", max_length=30),
                ),
                (
                    "number_cores",
                    models.IntegerField(help_text="кол-во ядер поцессора"),
                ),
                (
                    "processor_power",
                    models.IntegerField(help_text="разрядность процессора"),
                ),
                (
                    "battery_type",
                    models.CharField(
                        help_text="тип аккумулятора", max_length=20
                    ),
                ),
                (
                    "battery_capasity",
                    models.IntegerField(help_text="емкость аккумулятора"),
                ),
                (
                    "color",
                    models.CharField(
                        help_text="цвет модели телефона", max_length=30
                    ),
                ),
                (
                    "screen_size",
                    models.CharField(help_text="размер экрана", max_length=15),
                ),
                (
                    "camera",
                    models.CharField(
                        help_text="кол-во точек матрицы", max_length=30
                    ),
                ),
                (
                    "number_cameras",
                    models.IntegerField(help_text="цвет модели телефона"),
                ),
                (
                    "number_sim_cards",
                    models.IntegerField(help_text="кол-во SIM-карт"),
                ),
                (
                    "memory_card_support",
                    models.CharField(
                        help_text="поддержка дополнительной карты памяти",
                        max_length=3,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        help_text="страна производства", max_length=20
                    ),
                ),
                ("price", models.IntegerField(help_text="стоимость телефона")),
                ("release_date", models.DateField()),
            ],
        ),
    ]
