# Generated by Django 5.0.6 on 2024-06-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_Customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.SmallAutoField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="store_images",
                        verbose_name="Image",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("smartphone", "Смартфон"),
                            ("push_button_telephone", "Кнопочный телефон"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS")],
                        max_length=30,
                    ),
                ),
                ("version_os", models.CharField(max_length=30)),
                ("phone_model", models.CharField(max_length=30)),
                (
                    "cpu",
                    models.CharField(max_length=30, verbose_name="Процессор"),
                ),
                (
                    "number_cores",
                    models.IntegerField(verbose_name="Кол-во ядер поцессора"),
                ),
                (
                    "processor_power",
                    models.IntegerField(verbose_name="Разрядность процессора"),
                ),
                (
                    "battery_type",
                    models.CharField(
                        max_length=20, verbose_name="Тип аккумулятора"
                    ),
                ),
                (
                    "battery_capasity",
                    models.IntegerField(verbose_name="Емкость аккумулятора"),
                ),
                (
                    "color",
                    models.CharField(
                        max_length=30, verbose_name="Цвет модели телефона"
                    ),
                ),
                (
                    "screen_size",
                    models.CharField(
                        max_length=15, verbose_name="Размер экрана"
                    ),
                ),
                (
                    "camera",
                    models.CharField(
                        max_length=30, verbose_name="Кол-во точек матрицы"
                    ),
                ),
                (
                    "number_cameras",
                    models.IntegerField(verbose_name="Цвет модели телефона"),
                ),
                (
                    "number_sim_cards",
                    models.IntegerField(verbose_name="Кол-во SIM-карт"),
                ),
                (
                    "memory_card_support",
                    models.CharField(
                        max_length=3,
                        verbose_name="Поддержка дополнительной карты памяти",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        max_length=20, verbose_name="Страна производства"
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Стоимость")),
                ("release_date", models.DateField()),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=4,
                        verbose_name="Скидка в %",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание"
                    ),
                ),
            ],
        ),
    ]
