# Generated by Django 5.0.6 on 2024-06-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_Phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phone_case",
            fields=[
                (
                    "id",
                    models.SmallAutoField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="store_images",
                        verbose_name="Картинка",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        max_length=30, verbose_name="Модель чехла для телефона"
                    ),
                ),
                (
                    "color",
                    models.CharField(max_length=30, verbose_name="Цвет чехла"),
                ),
                (
                    "material",
                    models.CharField(
                        max_length=30, verbose_name="Материал чехла"
                    ),
                ),
                ("price", models.IntegerField()),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=4,
                        verbose_name="Скидка в %",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание"
                    ),
                ),
            ],
        ),
    ]
