# Generated by Django 4.2.7 on 2023-11-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone_case',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(help_text='модель чехла для телефона', max_length=30)),
                ('color', models.CharField(help_text='цвет чехла', max_length=30)),
                ('material', models.CharField(help_text='материал чехла', max_length=30)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'phone case',
                'db_table_comment': 'table about phone case',
            },
        ),
    ]
