# Generated by Django 4.2.7 on 2023-11-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_phone_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_fk', models.ManyToManyField(to='store.orders')),
                ('phone_fk', models.ManyToManyField(to='store.phone')),
            ],
        ),
    ]
